FROM ubuntu:18.04
#FROM debian:stable-slim
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update && apt-get -y install sshpass 

COPY configs  /app/configs
COPY migrations  /app/migrations
COPY templates  /app/templates
COPY docs  /app/docs

COPY rgru-file-uploader  /app/rgru-file-uploader

EXPOSE 7700

CMD bash -c "cd /app && ./rgru-file-uploader -serve 7700 -env=docker"




