version: '3.1'

services:


  # сервер, где запущено приложение
  runner:
    image: rgru/rgru-file-uploader:bare
    container_name: rgru-file-uploader-runner
    restart: always
    volumes:
      - images:/app/uploads

    # раскомментируйте следующую строку если хотите доступ только к публичному REST API 
    # command: bash -c "cd /app && ./rgru-file-uploader -serve 7700 -env=docker -front"
    ports:
      - 7700:7700
    depends_on:
      - db
      - redis
      - imgserver
    links:
      - db
      - redis
      - imgserver


volumes:
  images: