FROM golang:1.12.5-stretch 
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update && apt-get -y install sshpass 

WORKDIR /go/src/rgru-file-uploader
COPY . .

ENV GO111MODULE=on
RUN env CGO_ENABLED=0 go build

EXPOSE 7700

CMD ["./rgru-file-uploader", "-serve", "7700", "-env=docker"]

